config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("pages.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from .views import (
    HomePageView,
    AboutMePageView,
    WorksPageView,
    BlogPageView,
    BlogDetailPageView,
    RobotsTxtView,
    ContactPageView,
    SuccessPageView,
)

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("about/", AboutMePageView.as_view(), name="about"),
    path("works/", WorksPageView.as_view(), name="works"),
    path("blog/", BlogPageView.as_view(), name="blog"),
    path("blog/<slug:slug>/", BlogDetailPageView.as_view(), name="post_detail"),
    path("contact/", ContactPageView.as_view(), name="contact"),
    path("contact/success/", SuccessPageView.as_view(), name="success"),
    path("robots.txt", RobotsTxtView.as_view(content_type="text/plain"), name="robots"),
]

pages/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Project(models.Model):
    title = models.CharField(max_length=200)
    tech = models.TextField()
    cover = models.ImageField(upload_to="covers/", blank=True)

    def __str__(self):
        return self.title


class Post(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    cover = models.ImageField(upload_to="covers/", blank=True)
    slug = models.SlugField(null=False, unique=True)
    color = models.CharField(max_length=20, default='#fff', null=False, unique=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("post_detail", kwargs={"slug": self.slug})

pages/forms.py
from django import forms

class ContactForm(forms.Form):
    user_name = forms.CharField(required=True)
    user_email = forms.EmailField(required=True)
    user_subject = forms.CharField(required=True)
    user_message = forms.CharField(widget=forms.Textarea, required=True)

pages/views.py
from typing import Any
from django.views.generic import View, TemplateView, ListView, DetailView

from django.conf import settings
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .forms import ContactForm

from .models import Project, Post


class HomePageView(TemplateView):
    template_name = "pages/home.html"


class AboutMePageView(TemplateView):
    template_name = "pages/about_me.html"


class WorksPageView(ListView):
    model = Project
    template_name = "pages/works.html"


class BlogPageView(ListView):
    model = Post
    template_name = "pages/blog.html"


class BlogDetailPageView(DetailView):
    model = Post
    template_name = "pages/blog_detail.html"


class RobotsTxtView(TemplateView):
    template_name = "robots.txt"


class ContactPageView(View):
    def get(self, request):
        form = ContactForm()
        return render(request, "pages/contact.html", {"form": form})

    def post(self, request):
        form = ContactForm(request.POST)
        if form.is_valid():
            user_name = form.cleaned_data["user_name"]
            user_email = form.cleaned_data["user_email"]
            user_subject = form.cleaned_data["user_subject"]
            user_message = f'From: {user_email} \nMessage: {form.cleaned_data["user_message"]}'
            my_email = settings.DEFAULT_FROM_EMAIL
            my_subject = "Thank You for Reaching Out"
            my_message = f"Dear {user_name},\n\nThank you for contacting me through my portfolio. I wanted to acknowledge that I have received your message and will be responding to you shortly.\n\nI appreciate your interest and patience as I review your inquiry. I understand the importance of your message and will provide a prompt and thorough response.\n\nThank you for considering my portfolio, and I look forward to assisting you further.\n\nBest regards,\n\nSơn"
            try:
                send_mail(user_subject, user_message, my_email, [my_email])
                send_mail(my_subject, my_message, my_email, [user_email])
            except BadHeaderError:
                return HttpResponse("Invalid header found.")
            return redirect("success")
        return render(request, "pages/contact.html", {"form": form})

class SuccessPageView(TemplateView):
    template_name = "pages/success.html"

portfolios/views.py
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = "_base.html"

templates/_about_me.html
{% load static %}
<section class="grid max-w-2xl grid-cols-2 grid-rows-3 gap-10 mx-auto mt-16">
    <div class="flex flex-col items-center row-span-1 space-y-4 col-span-full">
        <svg width="56px"
             height="56px"
             viewBox="0 0 24 24"
             stroke-width="0.5"
             fill="none"
             xmlns="http://www.w3.org/2000/svg"
             color="#525252">
            <path d="M11.7 1.173a.6.6 0 01.6 0l8.926 5.154a.6.6 0 01.3.52v10.307a.6.6 0 01-.3.52L12.3 22.826a.6.6 0 01-.6 0l-8.926-5.154a.6.6 0 01-.3-.52V6.847a.6.6 0 01.3-.52L11.7 1.174z" stroke="#525252" stroke-width="0.5" stroke-linecap="round" stroke-linejoin="round">
            </path>
            <path d="M17 15H7l5-8 5 8z" stroke="#525252" stroke-width="0.5" stroke-linecap="round" stroke-linejoin="round"></path>
            <path d="M2.5 6.5L12 7M2.5 6.5L7 15M21.5 6.5L17 15M21.5 6.5L12 7V1M21.5 17.5L17 15M2.5 17.5L7 15M7 15l5 8 5-8" stroke="#525252" stroke-width="0.5" stroke-linejoin="round">
            </path>
        </svg>
        <p class="font-['Inter'] text-sm font-medium tracking-wide text-[#525252]">ABOUT ME SECTION</p>
        <div class="col-span-full row-span-1 text-center font-['Inter'] text-5xl font-medium text-white">Who Am I?</div>
    </div>
    <div class="col-span-1 row-span-2 flex flex-col items-center justify-around rounded-3xl border-t border-[#292929] bg-[#1a1a1a] p-2">
        <img src="{% static 'images/favicon.png' %}"
             alt=""
             class="w-72 rounded-xl bg-[#0f0f0f]" />
        <p class="font-['Caveat'] text-base text-[#848484]">I have talents that can't be put on resumes :))</p>
    </div>
    <div class="flex flex-col justify-between col-span-1 row-span-2">
        <div class="flex items-center pb-3 space-x-2">
            <p class="font-['Inter'] text-2xl font-medium text-white">Trinh The Son</p>
            <svg width="24px"
                 height="24px"
                 stroke-width="1"
                 viewBox="0 0 24 24"
                 fill="#1da1f2"
                 xmlns="http://www.w3.org/2000/svg"
                 color="#000000">
                <path d="M11.528 1.6a.6.6 0 01.944 0l1.809 2.3a.6.6 0 00.635.207l2.815-.798a.6.6 0 01.764.554l.11 2.925a.6.6 0 00.393.54l2.747 1.01a.6.6 0 01.292.897l-1.63 2.431a.6.6 0 000 .668l1.63 2.431a.6.6 0 01-.292.897l-2.747 1.01a.6.6 0 00-.392.54l-.111 2.925a.6.6 0 01-.764.554l-2.815-.798a.6.6 0 00-.636.206L12.473 22.4a.6.6 0 01-.944 0L9.72 20.1a.6.6 0 00-.635-.207l-2.815.798a.6.6 0 01-.764-.554l-.11-2.925a.6.6 0 00-.393-.54l-2.747-1.01a.6.6 0 01-.292-.897l1.63-2.431a.6.6 0 000-.668l-1.63-2.431a.6.6 0 01.292-.897l2.747-1.01a.6.6 0 00.392-.54l.111-2.925a.6.6 0 01.764-.554l2.815.798A.6.6 0 009.72 3.9L11.53 1.6z" stroke="#1da1f2" stroke-width="1">
                </path>
                <path d="M9 12l2 2 4-4" stroke="#fff" stroke-width="1" stroke-linecap="round" stroke-linejoin="round"></path>
            </svg>
        </div>
        <p class="text-justify font-['Wotfard'] text-lg text-[#858585]">
            Hello! I'm Son, a 4th-year Computer Science major at the University of Science, with a strong interest in full-stack development. Currently, the technologies I'm working with are <span id="n1">Javascript</span>, <span id="n2">Python</span>, and <span id="n3">Node.js</span>! I enjoy creating visually appealing and user-friendly applications.
        </p>
        <a href="{% static 'public/RESUME.pdf' %}"
           target="_blank"
           rel="noopener noreferrer"
           class="text-justify font-['Wotfard'] text-lg leading-relaxed text-[#772af4] underline">View my resume</a>
        <div class="w-[95%]">
            <p class="text-end font-['Grestelan'] text-3xl text-[#525252]">
                <span id="n4">Son</span>
            </p>
        </div>
    </div>
</section>

templates/_base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="author" content="Trinh The Son" />
    <meta name="description" content="Welcome to my portfolio! Hello, I'm Son, a 4th-year Computer Science major at HCMUS, with a strong interest in full-stack development." />
    <meta name="language" content="en" />
    <title>{% block title %}{% endblock %} Trinh The Son Portfolio</title>
    <link rel="shortcut icon" href="{% static 'images/asterisk.svg' %}" type="image/x-icon" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@700&family=Noto+Sans+SC:wght@700&family=Noto+Sans+KR:wght@700&display=swap" rel="stylesheet" media="print" onload="this.onload=null;this.removeAttribute('media');"/>
    {% block signature %}{% endblock signature %}
    {% tailwind_css %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}" media="print" onload="this.media='all'" />
    <link rel="stylesheet" href="{% static 'fonts/base.css' %}" media="print" onload="this.media='all'" />
  </head>
  <body class="bg-custom-black overflow-x-hidden !scroll-smooth antialiased transition-transform" x-data>
    <div>
      <div class="fixed top-0 left-0 w-full h-full">
        <div class="relative hidden w-full h-full bg-custom-black" @load.window="$el.classList.remove('hidden')">
          <div class="absolute bottom-0 left-0 right-0 top-0 bg-[linear-gradient(to_right,#4f4f4f2e_1px,transparent_1px),linear-gradient(to_bottom,#4f4f4f2e_1px,transparent_1px)] bg-[size:24px_24px] [mask-image:radial-gradient(ellipse_60%_50%_at_50%_0%,#0a0a0b,transparent_100%)]"></div>
        </div>
      </div>
      <div class="relative w-screen mx-auto">
        {% include 'partials/preloader.html' %}
        {% include 'partials/navbar.html' %}
        {% block content %}
        {% endblock content %}
      </div>
    </div>
    <script src="{% static "js/base.js" %}"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/@alpinejs/intersect@3.13.0/dist/cdn.min.js"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/@alpinejs/collapse@3.13.0/dist/cdn.min.js"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.13.0/dist/cdn.min.js"></script>
    <script>function playaudio(){return{currentlyPlaying:!1,playAndStop(){this.currentlyPlaying?(this.$refs.audio.pause(),this.$refs.audio.currentTime=0,this.currentlyPlaying=!1):(this.$refs.audio.play(),this.currentlyPlaying=!0)}}}</script>
    {% comment %} <script>
      const div = document.querySelector("body")
      window.addEventListener("mousemove", (e) => {
        let x = e.clientX;
        let windowWidth = window.innerWidth;
        let halfWindowWidth = windowWidth / 2;
        let translateX = x < halfWindowWidth ? (halfWindowWidth - x) / 12 : -(x - halfWindowWidth) / 12;
        div.style.transform = `translate(${translateX}px, 0)`;
      });
    </script> {% endcomment %}
    <script>
  const urls = {
    home: "{% url 'home' %}",
    about: "{% url 'about' %}",
    works: "{% url 'works' %}",
    blog: "{% url 'blog' %}",
    contact: "{% url 'contact' %}",
  };
</script>
  </body>
</html>

templates/_footer.html
<footer class="max-w-6xl mx-auto mt-16 -space-y-20">
    <div class="grid grid-rows-2">
        <div class="flex items-center justify-between rounded-t-3xl border border-[#292929] p-10">
            <div class="flex items-center justify-between space-x-10">
                <svg width="56px"
                     height="56px"
                     viewBox="0 0 24 24"
                     stroke-width="1"
                     fill="none"
                     xmlns="http://www.w3.org/2000/svg"
                     color="#525252">
                    <g clip-path="url(#send-diagonal_svg__clip0_2476_13290)" stroke="#525252" stroke-width="0.5" stroke-linecap="round" stroke-linejoin="round">
                    <path d="M22.152 3.553L11.178 21.004l-1.67-8.596L2 7.898l20.152-4.345zM9.456 12.444l12.696-8.89"></path>
                    </g>
                    <defs>
                    <clipPath id="send-diagonal_svg__clip0_2476_13290">
                    <path fill="#fff" d="M0 0h24v24H0z"></path>
                    </clipPath>
                    </defs>
                </svg>
                <p class="text-center font-['Inter'] text-[2.5rem] font-medium leading-tight text-white">Wanna work together?</p>
            </div>
            <a href="mailto:ttson.cs@gmail.com"
               class="transform rounded-full bg-[#772af4] px-8 py-4 font-['Inter'] text-2xl font-semibold text-white transition-colors duration-700 hover:bg-[#a06af7]">ttson.cs@gmail.com</a>
        </div>
        <div class="max-h-7 rounded-b-3xl border-b border-l border-r border-[#292929] bg-[#1a1a1a] p-[0.375rem] text-center font-['Inter'] text-xs font-medium uppercase text-[#525252]">
            Promise you that I’ll reply back within 24 hours.
        </div>
    </div>
    <div class="flex items-center justify-between">
        <div class="font-['Inter'] text-sm text-[#858585]">Copyright © 2023 Trinh The Son. All rights reserved.</div>
        <a href=""
           class="flex items-center space-x-2 rounded-full border border-[#292929] px-6 py-3">
            <svg width="20px"
                 height="20px"
                 viewBox="0 0 24 24"
                 stroke-width="1.5"
                 fill="none"
                 xmlns="http://www.w3.org/2000/svg"
                 color="#772af4">
                <path d="M17 11.6V15a6 6 0 01-6 6H9a6 6 0 01-6-6v-3.4a.6.6 0 01.6-.6h12.8a.6.6 0 01.6.6zM12 9c0-1 .714-2 2.143-2v0A2.857 2.857 0 0017 4.143V3.5M8 9v-.5a3 3 0 013-3v0a2 2 0 002-2V3" stroke="#772af4" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
                </path>
                <path d="M16 11h2.5a2.5 2.5 0 010 5H17" stroke="#772af4" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
                </path>
            </svg>
            <p class="font-['Inter'] text-sm font-medium text-white">Buy me a coffee</p>
        </a>
    </div>
</footer>

templates/_hero.html
{% load static %}
<main>
    <section class="grid-rows-8 mx-auto mt-3 grid max-h-[22rem] max-w-6xl grid-cols-6 gap-5">
        <div class="col-span-2 row-span-full space-y-5 rounded-3xl border-t border-[#292929] bg-[#1a1a1a] p-8">
            <div class="flex justify-between">
                <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ"
                   target="_blank"
                   rel="noopener noreferrer">
                    <img src="{% static 'images/favicon.png' %}"
                         alt=""
                         class="h-[4.75rem] w-[4.75rem] rounded-full bg-gradient-to-r from-indigo-300 to-purple-400 ring-4 ring-blue-500 ring-offset-4 ring-offset-[#1a1a1a]" />
                </a>
                <svg width="56px"
                     height="56px"
                     viewBox="0 0 24 24"
                     stroke-width="1"
                     fill="none"
                     xmlns="http://www.w3.org/2000/svg"
                     color="#525252">
                    <path d="M3 12h18m0 0l-8.5-8.5M21 12l-8.5 8.5" stroke="#525252" stroke-width="0.5" stroke-linecap="round" stroke-linejoin="round">
                    </path>
                </svg>
            </div>
            <p class="font-['Inter'] text-[2.5rem] font-medium leading-tight text-white">A Portfolio Brimming with Innovation</p>
            <p class="font-['Wotfard'] text-[#525252]">Trinh The Son &#x2022; Freelance</p>
        </div>
        <div class="col-span-2 row-span-3 rounded-3xl border-t border-[#292929] bg-[#1a1a1a] p-6">
            <div class="flex items-center justify-between">
                <div class="-space-y-2">
                    <p class="font-['Inter'] text-[1.75rem] font-medium text-[#525252]">Title</p>
                    {% comment %} <p class="animate-text bg-gradient-to-r from-fuchsia-600 to-pink-600 bg-clip-text font-['Inter'] text-[1.75rem] font-medium text-transparent">Back-End Dev</p> {% endcomment %}
                    <p class="animate-text text-white font-['Inter'] text-[1.75rem] font-medium">Back-End Dev</p>
                </div>
                <svg width="56px"
                     height="56px"
                     viewBox="0 0 24 24"
                     stroke-width="1"
                     fill="none"
                     xmlns="http://www.w3.org/2000/svg"
                     color="#000000">
                    <path d="M9 6v12M15 6v12M9 6a3 3 0 10-3 3h12a3 3 0 10-3-3M9 18a3 3 0 11-3-3h12a3 3 0 11-3 3" stroke="#525252" stroke-width="0.5" stroke-linecap="round" stroke-linejoin="round">
                    </path>
                </svg>
            </div>
        </div>
        <div class="col-span-2 col-end-7 row-span-full space-y-6 rounded-3xl border-t border-[#292929] bg-[#1a1a1a] px-8 py-10">
            <div class="flex justify-center">
                <svg width="56px"
                     height="56px"
                     viewBox="0 0 24 24"
                     stroke-width="1"
                     fill="none"
                     xmlns="http://www.w3.org/2000/svg"
                     color="#525252">
                    <g clip-path="url(#send-diagonal_svg__clip0_2476_13290)" stroke="#525252" stroke-width="0.5" stroke-linecap="round" stroke-linejoin="round">
                    <path d="M22.152 3.553L11.178 21.004l-1.67-8.596L2 7.898l20.152-4.345zM9.456 12.444l12.696-8.89"></path>
                    </g>
                    <defs><clipPath id="send-diagonal_svg__clip0_2476_13290">
                    <path fill="#fff" d="M0 0h24v24H0z"></path>
                    </clipPath></defs>
                </svg>
            </div>
            <p class="text-center font-['Inter'] text-[2.5rem] font-medium leading-tight text-white">Wanna work together?</p>
            <div class="flex flex-col items-center justify-center">
                <a href="mailto:ttson.cs@gmail.com"
                   target="_blank"
                   rel="noopener noreferrer"
                   class="transform rounded-full bg-[#772af4] px-8 py-4 font-['Inter'] text-2xl font-semibold text-white transition-colors duration-700 hover:bg-[#a06af7]">ttson.cs@gmail.com</a>
            </div>
        </div>
        <a href="https://linkedin.com/in/ttsoncs"
           target="_blank"
           rel="noopener noreferrer"
           class="col-span-1 row-span-2 flex items-center justify-center rounded-3xl border-t border-[#292929] bg-[#1a1a1a] p-6 font-['Inter'] text-[1.75rem] font-medium transition-colors duration-500 hover:bg-[#292929]">
            {% comment %} <div class="text-transparent bg-gradient-to-r from-cyan-500 to-blue-500 bg-clip-text">LinkedIn</div> {% endcomment %}
            <svg xmlns="http://www.w3.org/2000/svg"
                 width="36"
                 height="36"
                 viewBox="0 0 24 24"
                 style="fill: rgba(133, 133, 133, 1);
                        transform:;
                        msFilter:">
                <circle cx="4.983" cy="5.009" r="2.188"></circle>
                <path d="M9.237 8.855v12.139h3.769v-6.003c0-1.584.298-3.118 2.262-3.118 1.937 0 1.961 1.811 1.961 3.218v5.904H21v-6.657c0-3.27-.704-5.783-4.526-5.783-1.835 0-3.065 1.007-3.568 1.96h-.051v-1.66H9.237zm-6.142 0H6.87v12.139H3.095z">
                </path>
            </svg>
        </a>
        <a href="https://github.com/ttsoncs"
           target="_blank"
           rel="noopener noreferrer"
           class="col-span-1 row-span-2 flex items-center justify-center rounded-3xl border-t border-[#292929] bg-[#1a1a1a] p-6 font-['Inter'] text-[1.75rem] font-medium transition-colors duration-500 hover:bg-[#292929]">
            {% comment %} <div class="text-transparent bg-gradient-to-r from-amber-200 to-yellow-500 bg-clip-text">GitHub</div> {% endcomment %}
            <svg xmlns="http://www.w3.org/2000/svg"
                 width="36"
                 height="36"
                 viewBox="0 0 24 24"
                 style="fill: rgba(133, 133, 133, 1);
                        transform:;
                        msFilter:">
                <path fill-rule="evenodd" clip-rule="evenodd" d="M12.026 2c-5.509 0-9.974 4.465-9.974 9.974 0 4.406 2.857 8.145 6.821 9.465.499.09.679-.217.679-.481 0-.237-.008-.865-.011-1.696-2.775.602-3.361-1.338-3.361-1.338-.452-1.152-1.107-1.459-1.107-1.459-.905-.619.069-.605.069-.605 1.002.07 1.527 1.028 1.527 1.028.89 1.524 2.336 1.084 2.902.829.091-.645.351-1.085.635-1.334-2.214-.251-4.542-1.107-4.542-4.93 0-1.087.389-1.979 1.024-2.675-.101-.253-.446-1.268.099-2.64 0 0 .837-.269 2.742 1.021a9.582 9.582 0 0 1 2.496-.336 9.554 9.554 0 0 1 2.496.336c1.906-1.291 2.742-1.021 2.742-1.021.545 1.372.203 2.387.099 2.64.64.696 1.024 1.587 1.024 2.675 0 3.833-2.33 4.675-4.552 4.922.355.308.675.916.675 1.846 0 1.334-.012 2.41-.012 2.737 0 .267.178.577.687.479C19.146 20.115 22 16.379 22 11.974 22 6.465 17.535 2 12.026 2z">
                </path>
            </svg>
        </a>
        <div class="col-span-2 row-span-3 rounded-3xl border-t border-[#292929] bg-[#1a1a1a] p-6">
            <div class="flex items-center justify-between">
                <div class="-space-y-2">
                    <p class="font-['Inter'] text-[1.75rem] font-medium text-[#525252]">Based In</p>
                    <p class="font-['Inter'] text-[1.75rem] font-medium text-white">HCMC, Vietnam</p>
                </div>
                <svg width="56px"
                     height="56px"
                     stroke-width="1"
                     viewBox="0 0 24 24"
                     fill="none"
                     xmlns="http://www.w3.org/2000/svg"
                     color="#000000">
                    <path d="M2 12c0 5.523 4.477 10 10 10s10-4.477 10-10S17.523 2 12 2 2 6.477 2 12z" stroke="#525252" stroke-width="0.5" stroke-linecap="round" stroke-linejoin="round">
                    </path>
                    <path d="M13 2.05S16 6 16 12c0 6-3 9.95-3 9.95M11 21.95S8 18 8 12c0-6 3-9.95 3-9.95M2.63 15.5h18.74M2.63 8.5h18.74" stroke="#525252" stroke-width="0.5" stroke-linecap="round" stroke-linejoin="round">
                    </path>
                </svg>
            </div>
        </div>
    </section>
</main>

templates/about_me.html
{% extends "_base.html" %}
{% block title %}About Me - Trinh The Son Portfolio {% endblock %}
{% block content %}
    <div class="h-0 w-0 max-md:mt-20"></div>
    {% include 'about.html' %}
    <div class="h-0 w-0 mt-16"></div>
    {% include 'tech.html' %}
    <div class="h-0 w-0 mt-16"></div>
    {% include 'background.html' %}
    <div class="h-0 w-0 mt-16"></div>
{% endblock content %}

templates/contact.html
{% extends "_base.html" %}
{% block title %}Contact - Trinh The Son Portfolio {% endblock %}
{% block content %}
{% endblock content %}

templates/partials/hero_blog.html
{% load static %}
<section class="max-w-5xl px-6 mx-auto space-y-5">
  {% for post in post_list %}
  <div class="grid gap-5 lg:grid-cols-2">
    <div class="max-w-lg p-3 mx-auto space-y-3 transition-opacity duration-700 border-t opacity-0 bg-gray-bg border-t-gray-border rounded-2xl" x-intersect.half="$el.classList.add('opacity-100')">
      <div class="flex items-center justify-between px-2">
        <div class="flex flex-col">
          <h1 class="font-['Wotfard'] font-medium text-white text-lg md:text-xl">{{post.title}}</h1>
          <span class="text-gray-text-light font-['Wotfard'] text-sm md:text-base">{{post.created_at|date:'M d, Y'}}</span>
        </div>
        <a href="{% url "post_detail" post.slug %}"> <img src="{% static "images/arrow-gray.svg" %}" alt="arrow" class="w-5 h-5 md:w-6 md:h-6"> </a>
      </div>
      <div class="flex aspect-[4/3] w-full items-end justify-center rounded-xl" @load.window="$el.classList.add('{{post.color}}')"><img src="{{post.cover.url}}" alt="blog cover" class="w-11/12 rounded-t-lg" /></div>
    </div>
  </div>
  {% endfor %}
</section>

templates/partials/hero_works.html
{% load static %}
<section class="max-w-5xl px-6 mx-auto space-y-5">
  {% for project in project_list %}
  <div class="grid gap-5 lg:grid-cols-2">
    <div class="max-w-lg p-3 mx-auto space-y-3 transition-opacity duration-700 border-t opacity-0 bg-gray-bg border-t-gray-border rounded-2xl" x-intersect.half="$el.classList.add('opacity-100')">
      <div class="flex items-center justify-between px-2">
        <div class="flex flex-col">
          <span class="font-['Wotfard'] font-medium text-white text-lg md:text-xl">{{project.title}}</span>
          <span class="text-gray-text-light font-['Wotfard'] text-sm md:text-base">{{project.tech}}</span>
        </div>
        <a href="https://github.com/ttsoncs/Django-Portfolio-2023" target="_blank" rel="noopener noreferrer"> <img src="{% static "images/arrow-up.svg" %}" alt="arrow" class="w-5 h-5 md:w-6 md:h-6"> </a>
      </div>
      <div class="flex aspect-[4/3] w-full items-end justify-center rounded-xl bg-[#B993D6]"><img src="{{project.cover.url}}" alt="portfolio cover" class="w-11/12 rounded-t-lg" /></div>
    </div>
  </div>
  {% endfor %}
</section>